import logging
import json
from agents.base import BaseAgent

logger = logging.getLogger("agents.source_dispatch")

PUBLIC_SECTOR_PORTALS = [
    # --- UK WIDE / NATIONAL - CENTRAL GOVERNMENT & PARLIAMENT ---
    {"name": "Civil Service Jobs", "sector": "Civil Service - National", "url": "https://www.civilservicejobs.service.gov.uk/"},
    {"name": "UK Parliament Jobs", "sector": "Government", "url": "https://housesofparliament.tal.net/"},
    
    # --- LOCAL GOVERNMENT ---
    {"name": "Local Government Jobs (Jobsgopublic)", "sector": "Local Government - National", "url": "https://www.jobsgopublic.com/"},
    {"name": "Local Government Jobs (LGJobs)", "sector": "Local Government - National", "url": "https://www.lgjobs.com/"},
    
    # --- HEALTHCARE & SOCIAL CARE (ENGLAND & NATIONAL) ---
    {"name": "NHS Jobs", "sector": "NHS - England/Wales", "url": "https://www.jobs.nhs.uk/"},
    {"name": "NHS England Careers", "sector": "NHS - National", "url": "https://www.england.nhs.uk/about/working-for/how-to-apply/"},
    {"name": "NHS Blood and Transplant (NHSBT)", "sector": "NHS - National", "url": "https://www.nhsbt.nhs.uk/careers/"},
    {"name": "NHS Resolution", "sector": "NHS - National", "url": "https://resolution.nhs.uk/about-us/working-for-us/vacancies/"},
    {"name": "National Institute for Health and Care Excellence (NICE)", "sector": "Health - National", "url": "https://www.nice.org.uk/about/working-for-nice"},
    {"name": "UK Health Security Agency (UKHSA)", "sector": "Health - National", "url": "https://www.gov.uk/government/organisations/uk-health-security-agency/about/recruitment"},
    {"name": "Medicines and Healthcare products Regulatory Agency (MHRA)", "sector": "Health - National", "url": "https://www.gov.uk/government/organisations/medicines-and-healthcare-products-regulatory-agency/about/recruitment"},
    
    # --- EDUCATION & RESEARCH ---
    {"name": "jobs.ac.uk (Higher Education & Research)", "sector": "Education / Research - National", "url": "https://www.jobs.ac.uk/"},
    {"name": "UK Research and Innovation (UKRI)", "sector": "Research - National", "url": "https://careers.ukri.org/"},
    {"name": "Student Loans Company (SLC)", "sector": "Education - National", "url": "https://www.slc.co.uk/careers/"},
    {"name": "Education and Skills Funding Agency (ESFA)", "sector": "Education - National", "url": "https://www.gov.uk/government/organisations/education-and-skills-funding-agency/about/recruitment"},
    
    # --- TRANSPORT & INFRASTRUCTURE ---
    {"name": "Network Rail Careers", "sector": "Transport - National", "url": "https://www.networkrail.co.uk/careers/"},
    {"name": "National Highways", "sector": "Transport - National", "url": "https://careers.nationalhighways.co.uk/"},
    {"name": "High Speed Two (HS2)", "sector": "Transport - National", "url": "https://www.hs2.org.uk/careers/"},
    {"name": "East West Rail", "sector": "Transport - National", "url": "https://eastwestrail.co.uk/careers"},
    {"name": "Maritime and Coastguard Agency (MCA)", "sector": "Transport - Maritime", "url": "https://www.gov.uk/government/organisations/maritime-and-coastguard-agency/about/recruitment"},
    {"name": "Driver and Vehicle Licensing Agency (DVLA)", "sector": "Transport - National", "url": "https://www.gov.uk/government/organisations/driver-and-vehicle-licensing-agency/about/recruitment"},
    {"name": "Driver and Vehicle Standards Agency (DVSA)", "sector": "Transport - National", "url": "https://www.gov.uk/government/organisations/driver-and-vehicle-standards-agency/about/recruitment"},
    
    # --- JUSTICE, SECURITY & LAW ENFORCEMENT ---
    {"name": "Crown Prosecution Service (CPS)", "sector": "Justice - National", "url": "https://www.cps.gov.uk/careers"},
    {"name": "Judiciary Jobs", "sector": "Justice - National", "url": "https://www.judiciary.uk/about-the-judiciary/diversity/judicial-vacancies/"},
    {"name": "Serious Fraud Office (SFO)", "sector": "Justice - National", "url": "https://www.sfo.gov.uk/about-us/careers/"},
    {"name": "Supreme Court of the UK", "sector": "Justice - National", "url": "https://www.supremecourt.uk/about/vacancies.html"},
    {"name": "HM Courts & Tribunals Service (HMCTS)", "sector": "Justice - National", "url": "https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service/about/recruitment"},
    {"name": "HM Prison and Probation Service (HMPPS)", "sector": "Justice - National", "url": "https://prisonandprobationjobs.com/"},
    {"name": "Legal Aid Agency", "sector": "Justice - National", "url": "https://www.gov.uk/government/organisations/legal-aid-agency/about/recruitment"},
    {"name": "Security Service (MI5 / MI6 / GCHQ)", "sector": "Government Intelligence", "url": "https://www.mi5.gov.uk/careers"},
    {"name": "National Crime Agency (NCA)", "sector": "Law Enforcement - National", "url": "https://www.nationalcrimeagency.gov.uk/careers"},
    {"name": "College of Policing", "sector": "Law Enforcement - National", "url": "https://www.college.police.uk/careers"},
    {"name": "Independent Office for Police Conduct (IOPC)", "sector": "Law Enforcement - National", "url": "https://www.policeconduct.gov.uk/who-we-are/working-iopc/vacancies"},
    
    # --- REGULATORY, AGENCIES & INDEPENDENT BODIES ---
    {"name": "National Audit Office (NAO)", "sector": "Regulatory / Audit - National", "url": "https://www.nao.org.uk/careers/"},
    {"name": "Financial Conduct Authority (FCA)", "sector": "Regulatory - National", "url": "https://careers.fca.org.uk/"},
    {"name": "Bank of England", "sector": "Government - National", "url": "https://www.bankofengland.co.uk/careers"},
    {"name": "Competition and Markets Authority (CMA)", "sector": "Regulatory - Economic", "url": "https://www.gov.uk/government/organisations/competition-and-markets-authority/about/recruitment"},
    {"name": "Information Commissioner's Office (ICO)", "sector": "Regulatory - Data", "url": "https://ico.org.uk/about-the-ico/jobs/"},
    {"name": "Electoral Commission", "sector": "Regulatory - Elections", "url": "https://www.electoralcommission.org.uk/who-we-are-and-what-we-do/working-us/jobs"},
    {"name": "Equality and Human Rights Commission (EHRC)", "sector": "Regulatory - Rights", "url": "https://www.equalityhumanrights.com/en/about-us/jobs"},
    {"name": "Charity Commission", "sector": "Regulatory - Charities", "url": "https://www.gov.uk/government/organisations/charity-commission/about/recruitment"},
    {"name": "Health and Safety Executive (HSE)", "sector": "Regulatory - Safety", "url": "https://careers.hse.gov.uk/"},
    {"name": "Food Standards Agency (FSA)", "sector": "Regulatory - Food", "url": "https://www.food.gov.uk/about-us/careers"},
    {"name": "Social Work England", "sector": "Regulatory - Social Care", "url": "https://www.socialworkengland.org.uk/about/careers/"},
    {"name": "Ofsted Careers", "sector": "Regulatory - Education", "url": "https://www.gov.uk/government/organisations/ofsted/about/recruitment"},
    {"name": "Ofcom Careers", "sector": "Regulatory - Communications", "url": "https://www.ofcom.org.uk/about-ofcom/jobs"},
    {"name": "Ofgem Careers", "sector": "Regulatory - Energy", "url": "https://www.ofgem.gov.uk/careers"},
    {"name": "Ofwat Careers", "sector": "Regulatory - Water", "url": "https://www.ofwat.gov.uk/about-us/careers/"},
    {"name": "Care Quality Commission (CQC)", "sector": "Regulatory - Health", "url": "https://www.cqc.org.uk/about-us/jobs"},
    {"name": "Civil Aviation Authority (CAA)", "sector": "Regulatory - Aviation", "url": "https://careers.caa.co.uk/"},
    {"name": "Financial Ombudsman Service", "sector": "Regulatory - Financial", "url": "https://jobs.financial-ombudsman.org.uk/"},
    {"name": "UK Debt Management Office (DMO)", "sector": "Government - Financial", "url": "https://www.dmo.gov.uk/about/careers/"},
    
    # --- ENVIRONMENT, RURAL & MAPPING ---
    {"name": "Environment Agency", "sector": "Environment - England", "url": "https://environmentagencycareers.co.uk/"},
    {"name": "Animal and Plant Health Agency (APHA)", "sector": "Environment - National", "url": "https://www.gov.uk/government/organisations/animal-and-plant-health-agency/about/recruitment"},
    {"name": "Rural Payments Agency (RPA)", "sector": "Environment - National", "url": "https://www.gov.uk/government/organisations/rural-payments-agency/about/recruitment"},
    {"name": "Marine Management Organisation (MMO)", "sector": "Environment - National", "url": "https://www.gov.uk/government/organisations/marine-management-organisation/about/recruitment"},
    {"name": "Forestry Commission", "sector": "Environment - England", "url": "https://www.gov.uk/government/organisations/forestry-commission/about/recruitment"},
    {"name": "Crown Estate", "sector": "Environment - National", "url": "https://www.thecrownestate.co.uk/en-gb/careers/"},
    {"name": "Ordnance Survey", "sector": "Mapping - National", "url": "https://www.ordnancesurvey.co.uk/about/careers"},
    {"name": "HM Land Registry", "sector": "Land - National", "url": "https://www.gov.uk/government/organisations/land-registry/about/recruitment"},
    {"name": "Valuation Office Agency (VOA)", "sector": "Land - National", "url": "https://www.gov.uk/government/organisations/valuation-office-agency/about/recruitment"},
    
    # --- HOUSING, ARTS, CULTURE & SCIENCE ---
    {"name": "Homes England", "sector": "Housing - England", "url": "https://www.gov.uk/government/organisations/homes-england/about/recruitment"},
    {"name": "Arts Council England", "sector": "Arts - England", "url": "https://www.artscouncil.org.uk/about-us/jobs-and-careers"},
    {"name": "Sport England", "sector": "Sport - England", "url": "https://www.sportengland.org/careers"},
    {"name": "UK Sport", "sector": "Sport - National", "url": "https://www.uksport.gov.uk/jobs-in-sport"},
    {"name": "Historic England", "sector": "Heritage - England", "url": "https://historicengland.org.uk/about/jobs/"},
    {"name": "British Library", "sector": "Culture - National", "url": "https://www.bl.uk/careers/"},
    {"name": "British Museum", "sector": "Culture - National", "url": "https://www.britishmuseum.org/about-us/jobs"},
    {"name": "Victoria and Albert Museum (V&A)", "sector": "Culture - National", "url": "https://www.vam.ac.uk/info/jobs"},
    {"name": "Tate", "sector": "Culture - National", "url": "https://workingat.tate.org.uk/"},
    {"name": "Natural History Museum", "sector": "Culture - National", "url": "https://careers.nhm.ac.uk/"},
    {"name": "BBC Careers", "sector": "Public Broadcasting", "url": "https://careerssearch.bbc.co.uk/"},
    {"name": "UK Space Agency", "sector": "Science - National", "url": "https://www.gov.uk/government/organisations/uk-space-agency/about/recruitment"},
    
    # --- REGIONAL TRANSPORT, BLUE LIGHT & AUTHORITIES (ENGLAND) ---
    {"name": "Transport for London (TfL)", "sector": "Transport - London", "url": "https://careers.tfl.gov.uk/"},
    {"name": "Greater London Authority (GLA)", "sector": "Local Government - London", "url": "https://www.london.gov.uk/about-us/jobs-and-careers"},
    {"name": "Metropolitan Police Careers", "sector": "Police - London", "url": "https://www.met.police.uk/car/careers/"},
    {"name": "Transport for Greater Manchester (TfGM)", "sector": "Transport - Manchester", "url": "https://tfgm.com/careers"},
    {"name": "West Midlands Combined Authority (WMCA)", "sector": "Local Government - Midlands", "url": "https://www.wmca.org.uk/careers/"},

    # --- SCOTLAND ---
    {"name": "Work for Scotland (Scottish Government)", "sector": "Civil Service - Scotland", "url": "https://work-for-scotland.org/"},
    {"name": "Scottish Government Careers", "sector": "Government - Scotland", "url": "https://www.gov.scot/about/jobs/"},
    {"name": "NHS Scotland Jobs", "sector": "NHS - Scotland", "url": "https://jobs.scot.nhs.uk/"},
    {"name": "MyJobScotland (Local Gov)", "sector": "Local Government - Scotland", "url": "https://www.myjobscotland.gov.uk/"},
    {"name": "Audit Scotland", "sector": "Regulatory / Audit - Scotland", "url": "https://www.audit-scotland.gov.uk/careers"},
    {"name": "Police Scotland Careers", "sector": "Police - Scotland", "url": "https://www.scotland.police.uk/recruitment/"},
    {"name": "Scottish Enterprise", "sector": "Economic Development - Scotland", "url": "https://www.scottish-enterprise.com/about-us/careers"},
    {"name": "Scottish Environment Protection Agency (SEPA)", "sector": "Environment - Scotland", "url": "https://www.sepa.org.uk/jobs/"},
    {"name": "NatureScot", "sector": "Environment - Scotland", "url": "https://www.nature.scot/about-us/jobs"},
    {"name": "Scottish Water", "sector": "Utilities - Scotland", "url": "https://scottishwater.wd3.myworkdayjobs.com/External_Careers"},
    {"name": "Scottish Qualifications Authority (SQA)", "sector": "Education - Scotland", "url": "https://www.sqa.org.uk/sqa/98642.html"},
    {"name": "Skills Development Scotland", "sector": "Education - Scotland", "url": "https://www.skillsdevelopmentscotland.co.uk/careers/"},
    {"name": "National Library of Scotland", "sector": "Culture - Scotland", "url": "https://www.nls.uk/about-us/working-here/"},
    {"name": "National Galleries of Scotland", "sector": "Culture - Scotland", "url": "https://www.nationalgalleries.org/jobs"},
    
    # --- WALES ---
    {"name": "Welsh Government Jobs", "sector": "Civil Service - Wales", "url": "https://www.gov.wales/welsh-government-jobs"},
    {"name": "NHS Wales Jobs", "sector": "NHS - Wales", "url": "https://www.jobs.nhs.wales/"},
    {"name": "Public Health Wales", "sector": "Health - Wales", "url": "https://phw.nhs.wales/about-us/working-for-us/"},
    {"name": "Audit Wales", "sector": "Regulatory / Audit - Wales", "url": "https://www.audit.wales/careers"},
    {"name": "Natural Resources Wales", "sector": "Environment - Wales", "url": "https://naturalresources.wales/about-us/jobs/"},
    {"name": "South Wales Police", "sector": "Police - Wales", "url": "https://www.south-wales.police.uk/police-forces/south-wales-police/areas/careers/careers/"},
    {"name": "Transport for Wales", "sector": "Transport - Wales", "url": "https://tfw.wales/about-us/careers"},
    {"name": "National Library of Wales", "sector": "Culture - Wales", "url": "https://www.library.wales/about-us/jobs"},
    {"name": "National Museum Wales (Amgueddfa Cymru)", "sector": "Culture - Wales", "url": "https://museum.wales/jobs/"},
    
    # --- NORTHERN IRELAND ---
    {"name": "NICS Recruitment (NI Civil Service)", "sector": "Civil Service - NI", "url": "https://irecruit-ext.hrconnect.nigov.net/"},
    {"name": "Northern Ireland Assembly Careers", "sector": "Government - NI", "url": "https://www.niassembly.gov.uk/about-the-assembly/recruitment/"},
    {"name": "HSCNI Jobs (NHS NI)", "sector": "NHS - NI", "url": "https://jobs.hscni.net/"},
    {"name": "Public Health Agency (NI)", "sector": "Health - NI", "url": "https://www.publichealth.hscni.net/about-us/working-pha"},
    {"name": "Local Government Jobs NI", "sector": "Local Government - NI", "url": "https://www.localgovernmentjobsni.gov.uk/"},
    {"name": "Northern Ireland Audit Office", "sector": "Regulatory / Audit - NI", "url": "https://www.niauditoffice.gov.uk/careers"},
    {"name": "Police Service of Northern Ireland (PSNI)", "sector": "Police - NI", "url": "https://www.joinpsni.co.uk/"},
    {"name": "Education Authority Northern Ireland", "sector": "Education - NI", "url": "https://eani.taleo.net/careersection/external/jobsearch.ftl"},
    {"name": "Northern Ireland Housing Executive", "sector": "Housing - NI", "url": "https://www.nihe.gov.uk/about-us/careers"},
    {"name": "Invest Northern Ireland", "sector": "Economic Development - NI", "url": "https://www.investni.com/about-us/careers"},
    {"name": "Translink NI", "sector": "Transport - NI", "url": "https://www.translink.co.uk/workwithus"}
,

    # --- MORE HEALTH & SOCIAL CARE REGULATORS ---
    {"name": "Care Inspectorate (Scotland)", "sector": "Health - Scotland", "url": "https://www.careinspectorate.com/index.php/jobs"},
    {"name": "Care Inspectorate Wales", "sector": "Health - Wales", "url": "https://careinspectorate.wales/about-us/working-for-us"},
    {"name": "Scottish Social Services Council (SSSC)", "sector": "Social Care - Scotland", "url": "https://www.sssc.uk.com/about-the-sssc/working-for-us/"},
    {"name": "Healthcare Improvement Scotland", "sector": "Health - Scotland", "url": "https://www.healthcareimprovementscotland.org/about_us/work_with_us.aspx"},
    {"name": "Northern Ireland Blood Transfusion Service", "sector": "Health - NI", "url": "https://www.nibts.hscni.net/about-us/working-for-us/"},
    {"name": "Northern Ireland Social Care Council", "sector": "Social Care - NI", "url": "https://niscc.info/about-us/working-for-us/"},
    {"name": "Human Tissue Authority (HTA)", "sector": "Health - National", "url": "https://www.hta.gov.uk/about-us/working-for-us"},
    {"name": "Human Fertilisation and Embryology Authority (HFEA)", "sector": "Health - National", "url": "https://www.hfea.gov.uk/about-us/working-for-us/"},
    {"name": "Nursing and Midwifery Council (NMC)", "sector": "Health - National", "url": "https://www.nmc.org.uk/about-us/working-for-us/"},
    {"name": "General Medical Council (GMC)", "sector": "Health - National", "url": "https://jobs.gmc-uk.org/"},
    {"name": "Health Research Authority (HRA)", "sector": "Health - National", "url": "https://www.hra.nhs.uk/about-us/working-for-us/"},

    # --- MORE ENVIRONMENT, FOOD & RURAL ---
    {"name": "Food Standards Scotland", "sector": "Regulatory - Scotland", "url": "https://www.foodstandards.gov.scot/about-us/jobs"},
    {"name": "Joint Nature Conservation Committee (JNCC)", "sector": "Environment - National", "url": "https://jncc.gov.uk/about-jncc/careers/"},
    {"name": "Consumer Council for Water (CCW)", "sector": "Environment - National", "url": "https://www.ccw.org.uk/about-us/careers/"},
    {"name": "Agriculture and Horticulture Development Board (AHDB)", "sector": "Agriculture - National", "url": "https://ahdb.org.uk/careers"},
    {"name": "Sea Fish Industry Authority (Seafish)", "sector": "Environment - National", "url": "https://www.seafish.org/about-us/careers/"},
    {"name": "Water Industry Commission for Scotland (WICS)", "sector": "Regulatory - Scotland", "url": "https://www.wics.scot/about-us/careers"},
    {"name": "Fera Science", "sector": "Environment - National", "url": "https://www.fera.co.uk/about-us/careers"},

    # --- MORE LEGAL, JUSTICE & POLICE ---
    {"name": "Scottish Prison Service (SPS)", "sector": "Justice - Scotland", "url": "https://www.sps.gov.uk/careers/"},
    {"name": "Scottish Courts and Tribunals Service (SCTS)", "sector": "Justice - Scotland", "url": "https://www.scotcourts.gov.uk/about-the-scottish-court-service/recruitment"},
    {"name": "Crown Office and Procurator Fiscal Service (COPFS)", "sector": "Justice - Scotland", "url": "https://www.copfs.gov.uk/careers/"},
    {"name": "Northern Ireland Courts and Tribunals Service (NICTS)", "sector": "Justice - NI", "url": "https://www.justice-ni.gov.uk/topics/courts-and-tribunals"},
    {"name": "Probation Board for Northern Ireland (PBNI)", "sector": "Justice - NI", "url": "https://www.pbni.org.uk/working-for-us/"},
    {"name": "Judicial Appointments Commission (JAC)", "sector": "Justice - National", "url": "https://judicialappointments.gov.uk/about-the-jac/working-for-the-jac/"},
    {"name": "Criminal Cases Review Commission (CCRC)", "sector": "Justice - National", "url": "https://ccrc.gov.uk/about-us/jobs/"},
    {"name": "Scottish Criminal Cases Review Commission", "sector": "Justice - Scotland", "url": "https://www.sccrc.co.uk/about-us/vacancies"},
    {"name": "Police Investigations & Review Commissioner (PIRC)", "sector": "Law Enforcement - Scotland", "url": "https://pirc.scot/about-us/careers/"},
    {"name": "Northern Ireland Policing Board", "sector": "Law Enforcement - NI", "url": "https://www.nipolicingboard.org.uk/vacancies"},
    {"name": "Office of the Public Guardian (OPG)", "sector": "Justice - National", "url": "https://www.gov.uk/government/organisations/office-of-the-public-guardian/about/recruitment"},
    {"name": "Registers of Scotland", "sector": "Justice - Scotland", "url": "https://www.ros.gov.uk/about-us/careers"},

    # --- MORE CULTURE, MUSEUMS & TOURISM ---
    {"name": "VisitBritain / VisitEngland", "sector": "Tourism - National", "url": "https://www.visitbritain.org/about-us/careers"},
    {"name": "VisitScotland", "sector": "Tourism - Scotland", "url": "https://www.visitscotland.org/about-us/careers"},
    {"name": "Tourism Northern Ireland", "sector": "Tourism - NI", "url": "https://tourismni.com/about-us/careers/"},
    {"name": "National Museums Scotland", "sector": "Culture - Scotland", "url": "https://www.nms.ac.uk/about-us/jobs-and-volunteering/"},
    {"name": "National Museums NI", "sector": "Culture - NI", "url": "https://www.nationalmuseumsni.org/careers"},
    {"name": "Royal Armouries", "sector": "Culture - National", "url": "https://royalarmouries.org/about-us/vacancies/"},
    {"name": "Wallace Collection", "sector": "Culture - National", "url": "https://www.wallacecollection.org/about-us/opportunities/"},
    {"name": "Horniman Museum", "sector": "Culture - National", "url": "https://www.horniman.ac.uk/about-us/jobs/"},
    {"name": "Royal Botanic Gardens, Kew", "sector": "Culture/Science - National", "url": "https://www.kew.org/about-us/jobs"},
    {"name": "Royal Botanic Garden Edinburgh", "sector": "Culture/Science - Scotland", "url": "https://www.rbge.org.uk/about-us/working-with-us/vacancies/"},
    {"name": "Science Museum Group", "sector": "Culture - National", "url": "https://www.sciencemuseumgroup.org.uk/careers/"},
    {"name": "Imperial War Museums", "sector": "Culture - National", "url": "https://www.iwm.org.uk/jobs"},
    {"name": "Royal Parks", "sector": "Culture - London", "url": "https://www.royalparks.org.uk/about-us/careers"},

    # --- MORE TRANSPORT & INFRASTRUCTURE ---
    {"name": "Office of Rail and Road (ORR)", "sector": "Regulatory - Transport", "url": "https://www.orr.gov.uk/about/careers"},
    {"name": "Northern Lighthouse Board", "sector": "Transport - Scotland", "url": "https://www.nlb.org.uk/who-we-are/careers/"},
    {"name": "Trinity House", "sector": "Transport - National", "url": "https://www.trinityhouse.co.uk/about-us/careers"},
    {"name": "Scottish Canals", "sector": "Transport - Scotland", "url": "https://www.scottishcanals.co.uk/corporate/about-us/careers"},
    {"name": "Caledonian MacBrayne (CalMac)", "sector": "Transport - Scotland", "url": "https://www.calmac.co.uk/careers"},

    # --- MORE REGULATORS, BUSINESS & ECONOMY ---
    {"name": "The Pensions Regulator (TPR)", "sector": "Regulatory - Financial", "url": "https://www.thepensionsregulator.gov.uk/en/about-us/working-for-us"},
    {"name": "Financial Reporting Council (FRC)", "sector": "Regulatory - Financial", "url": "https://www.frc.org.uk/about-the-frc/careers"},
    {"name": "Single Source Regulations Office (SSRO)", "sector": "Regulatory - Defence", "url": "https://www.gov.uk/government/organisations/single-source-regulations-office/about/recruitment"},
    {"name": "UK Export Finance (UKEF)", "sector": "Government - Financial", "url": "https://www.gov.uk/government/organisations/uk-export-finance/about/recruitment"},
    {"name": "British Business Bank", "sector": "Government - Financial", "url": "https://www.british-business-bank.co.uk/about-us/careers/"},
    {"name": "Scottish Funding Council (SFC)", "sector": "Education - Scotland", "url": "https://www.sfc.ac.uk/about-us/working-for-sfc/"},
    {"name": "Medr (Tertiary Education and Research Commission for Wales)", "sector": "Education - Wales", "url": "https://medr.cymru/"},
    {"name": "Government Digital Service (GDS)", "sector": "Government - Tech", "url": "https://www.gov.uk/government/organisations/government-digital-service/about/recruitment"},
    {"name": "UK Statistics Authority", "sector": "Government - National", "url": "https://uksa.statisticsauthority.gov.uk/about-the-authority/vacancies/"},
    {"name": "Civil Service Commission", "sector": "Government - National", "url": "https://civilservicecommission.independent.gov.uk/about-us/vacancies/"}
,

    # --- 100 MAJOR UK UNIVERSITIES ---
    {"name": "Ox University", "sector": "Education", "url": "https://www.ox.ac.uk"},
    {"name": "Cam University", "sector": "Education", "url": "https://www.cam.ac.uk"},
    {"name": "Ucl University", "sector": "Education", "url": "https://www.ucl.ac.uk"},
    {"name": "Imperial University", "sector": "Education", "url": "https://www.imperial.ac.uk"},
    {"name": "Ed University", "sector": "Education", "url": "https://www.ed.ac.uk"},
    {"name": "Manchester University", "sector": "Education", "url": "https://www.manchester.ac.uk"},
    {"name": "Kcl University", "sector": "Education", "url": "https://www.kcl.ac.uk"},
    {"name": "Lse University", "sector": "Education", "url": "https://www.lse.ac.uk"},
    {"name": "Bristol University", "sector": "Education", "url": "https://www.bristol.ac.uk"},
    {"name": "Warwick University", "sector": "Education", "url": "https://www.warwick.ac.uk"},
    {"name": "Southampton University", "sector": "Education", "url": "https://www.southampton.ac.uk"},
    {"name": "Glasgow University", "sector": "Education", "url": "https://www.glasgow.ac.uk"},
    {"name": "Leeds University", "sector": "Education", "url": "https://www.leeds.ac.uk"},
    {"name": "Bham University", "sector": "Education", "url": "https://www.bham.ac.uk"},
    {"name": "Sheffield University", "sector": "Education", "url": "https://www.sheffield.ac.uk"},
    {"name": "Nottingham University", "sector": "Education", "url": "https://www.nottingham.ac.uk"},
    {"name": "Qmul University", "sector": "Education", "url": "https://www.qmul.ac.uk"},
    {"name": "York University", "sector": "Education", "url": "https://www.york.ac.uk"},
    {"name": "Lancaster University", "sector": "Education", "url": "https://www.lancaster.ac.uk"},
    {"name": "Ncl University", "sector": "Education", "url": "https://www.ncl.ac.uk"},
    {"name": "Exeter University", "sector": "Education", "url": "https://www.exeter.ac.uk"},
    {"name": "Cardiff University", "sector": "Education", "url": "https://www.cardiff.ac.uk"},
    {"name": "Bath University", "sector": "Education", "url": "https://www.bath.ac.uk"},
    {"name": "Liverpool University", "sector": "Education", "url": "https://www.liverpool.ac.uk"},
    {"name": "Reading University", "sector": "Education", "url": "https://www.reading.ac.uk"},
    {"name": "Abdn University", "sector": "Education", "url": "https://www.abdn.ac.uk"},
    {"name": "Qub University", "sector": "Education", "url": "https://www.qub.ac.uk"},
    {"name": "Sussex University", "sector": "Education", "url": "https://www.sussex.ac.uk"},
    {"name": "Lboro University", "sector": "Education", "url": "https://www.lboro.ac.uk"},
    {"name": "Le University", "sector": "Education", "url": "https://www.le.ac.uk"},
    {"name": "Strath University", "sector": "Education", "url": "https://www.strath.ac.uk"},
    {"name": "Dundee University", "sector": "Education", "url": "https://www.dundee.ac.uk"},
    {"name": "St-Andrews University", "sector": "Education", "url": "https://www.st-andrews.ac.uk"},
    {"name": "Swansea University", "sector": "Education", "url": "https://www.swansea.ac.uk"},
    {"name": "Uea University", "sector": "Education", "url": "https://www.uea.ac.uk"},
    {"name": "Surrey University", "sector": "Education", "url": "https://www.surrey.ac.uk"},
    {"name": "Rhul University", "sector": "Education", "url": "https://www.rhul.ac.uk"},
    {"name": "Essex University", "sector": "Education", "url": "https://www.essex.ac.uk"},
    {"name": "Kent University", "sector": "Education", "url": "https://www.kent.ac.uk"},
    {"name": "Brunel University", "sector": "Education", "url": "https://www.brunel.ac.uk"},
    {"name": "Bbk University", "sector": "Education", "url": "https://www.bbk.ac.uk"},
    {"name": "City University", "sector": "Education", "url": "https://www.city.ac.uk"},
    {"name": "Gold University", "sector": "Education", "url": "https://www.gold.ac.uk"},
    {"name": "Sgul University", "sector": "Education", "url": "https://www.sgul.ac.uk"},
    {"name": "Soas University", "sector": "Education", "url": "https://www.soas.ac.uk"},
    {"name": "Rvc University", "sector": "Education", "url": "https://www.rvc.ac.uk"},
    {"name": "Aston University", "sector": "Education", "url": "https://www.aston.ac.uk"},
    {"name": "Keele University", "sector": "Education", "url": "https://www.keele.ac.uk"},
    {"name": "Hull University", "sector": "Education", "url": "https://www.hull.ac.uk"},
    {"name": "Bradford University", "sector": "Education", "url": "https://www.bradford.ac.uk"},
    {"name": "Salford University", "sector": "Education", "url": "https://www.salford.ac.uk"},
    {"name": "Mmu University", "sector": "Education", "url": "https://www.mmu.ac.uk"},
    {"name": "Ntu University", "sector": "Education", "url": "https://www.ntu.ac.uk"},
    {"name": "Shu University", "sector": "Education", "url": "https://www.shu.ac.uk"},
    {"name": "Derby University", "sector": "Education", "url": "https://www.derby.ac.uk"},
    {"name": "Lincoln University", "sector": "Education", "url": "https://www.lincoln.ac.uk"},
    {"name": "Port University", "sector": "Education", "url": "https://www.port.ac.uk"},
    {"name": "Bournemouth University", "sector": "Education", "url": "https://www.bournemouth.ac.uk"},
    {"name": "Plymouth University", "sector": "Education", "url": "https://www.plymouth.ac.uk"},
    {"name": "Uwe University", "sector": "Education", "url": "https://www.uwe.ac.uk"},
    {"name": "Glos University", "sector": "Education", "url": "https://www.glos.ac.uk"},
    {"name": "Worc University", "sector": "Education", "url": "https://www.worc.ac.uk"},
    {"name": "Coventry University", "sector": "Education", "url": "https://www.coventry.ac.uk"},
    {"name": "Staffs University", "sector": "Education", "url": "https://www.staffs.ac.uk"},
    {"name": "Wlv University", "sector": "Education", "url": "https://www.wlv.ac.uk"},
    {"name": "Bcu University", "sector": "Education", "url": "https://www.bcu.ac.uk"},
    {"name": "Chester University", "sector": "Education", "url": "https://www.chester.ac.uk"},
    {"name": "Edgehill University", "sector": "Education", "url": "https://www.edgehill.ac.uk"},
    {"name": "Uclan University", "sector": "Education", "url": "https://www.uclan.ac.uk"},
    {"name": "Cumbria University", "sector": "Education", "url": "https://www.cumbria.ac.uk"},
    {"name": "Sunderland University", "sector": "Education", "url": "https://www.sunderland.ac.uk"},
    {"name": "Tees University", "sector": "Education", "url": "https://www.tees.ac.uk"},
    {"name": "Northumbria University", "sector": "Education", "url": "https://www.northumbria.ac.uk"},
    {"name": "Leedsbeckett University", "sector": "Education", "url": "https://www.leedsbeckett.ac.uk"},
    {"name": "Hud University", "sector": "Education", "url": "https://www.hud.ac.uk"},
    {"name": "Winchester University", "sector": "Education", "url": "https://www.winchester.ac.uk"},
    {"name": "Solent University", "sector": "Education", "url": "https://www.solent.ac.uk"},
    {"name": "Roehampton University", "sector": "Education", "url": "https://www.roehampton.ac.uk"},
    {"name": "Kingston University", "sector": "Education", "url": "https://www.kingston.ac.uk"},
    {"name": "Mdx University", "sector": "Education", "url": "https://www.mdx.ac.uk"},
    {"name": "Uel University", "sector": "Education", "url": "https://www.uel.ac.uk"},
    {"name": "Lsbu University", "sector": "Education", "url": "https://www.lsbu.ac.uk"},
    {"name": "Westminster University", "sector": "Education", "url": "https://www.westminster.ac.uk"},
    {"name": "Uwl University", "sector": "Education", "url": "https://www.uwl.ac.uk"},
    {"name": "Greenwich University", "sector": "Education", "url": "https://www.greenwich.ac.uk"},
    {"name": "Southwales University", "sector": "Education", "url": "https://www.southwales.ac.uk"},
    {"name": "Cardiffmet University", "sector": "Education", "url": "https://www.cardiffmet.ac.uk"},
    {"name": "Bangor University", "sector": "Education", "url": "https://www.bangor.ac.uk"},
    {"name": "Aber University", "sector": "Education", "url": "https://www.aber.ac.uk"},
    {"name": "Glyndwr University", "sector": "Education", "url": "https://www.glyndwr.ac.uk"},
    {"name": "Uwtsd University", "sector": "Education", "url": "https://www.uwtsd.ac.uk"},
    {"name": "Rgu University", "sector": "Education", "url": "https://www.rgu.ac.uk"},
    {"name": "Napier University", "sector": "Education", "url": "https://www.napier.ac.uk"},
    {"name": "Qmu University", "sector": "Education", "url": "https://www.qmu.ac.uk"},
    {"name": "Gcu University", "sector": "Education", "url": "https://www.gcu.ac.uk"},
    {"name": "Uws University", "sector": "Education", "url": "https://www.uws.ac.uk"},
    {"name": "Ulster University", "sector": "Education", "url": "https://www.ulster.ac.uk"},
    {"name": "Hope University", "sector": "Education", "url": "https://www.hope.ac.uk"},
    {"name": "Bolton University", "sector": "Education", "url": "https://www.bolton.ac.uk"},
    {"name": "Beds University", "sector": "Education", "url": "https://www.beds.ac.uk"},

    # --- 120 MAJOR UK LOCAL AUTHORITIES / COUNCILS ---
    {"name": "Birmingham Council", "sector": "Local Government", "url": "https://www.birmingham.gov.uk"},
    {"name": "Leeds Council", "sector": "Local Government", "url": "https://www.leeds.gov.uk"},
    {"name": "Glasgow Council", "sector": "Local Government", "url": "https://www.glasgow.gov.uk"},
    {"name": "Sheffield Council", "sector": "Local Government", "url": "https://www.sheffield.gov.uk"},
    {"name": "Bradford Council", "sector": "Local Government", "url": "https://www.bradford.gov.uk"},
    {"name": "Manchester Council", "sector": "Local Government", "url": "https://www.manchester.gov.uk"},
    {"name": "Edinburgh Council", "sector": "Local Government", "url": "https://www.edinburgh.gov.uk"},
    {"name": "Liverpool Council", "sector": "Local Government", "url": "https://www.liverpool.gov.uk"},
    {"name": "Bristol Council", "sector": "Local Government", "url": "https://www.bristol.gov.uk"},
    {"name": "Cardiff Council", "sector": "Local Government", "url": "https://www.cardiff.gov.uk"},
    {"name": "Croydon Council", "sector": "Local Government", "url": "https://www.croydon.gov.uk"},
    {"name": "Barnet Council", "sector": "Local Government", "url": "https://www.barnet.gov.uk"},
    {"name": "Leicester Council", "sector": "Local Government", "url": "https://www.leicester.gov.uk"},
    {"name": "Ealing Council", "sector": "Local Government", "url": "https://www.ealing.gov.uk"},
    {"name": "Newham Council", "sector": "Local Government", "url": "https://www.newham.gov.uk"},
    {"name": "Brent Council", "sector": "Local Government", "url": "https://www.brent.gov.uk"},
    {"name": "Wandsworth Council", "sector": "Local Government", "url": "https://www.wandsworth.gov.uk"},
    {"name": "Wakefield Council", "sector": "Local Government", "url": "https://www.wakefield.gov.uk"},
    {"name": "Bromley Council", "sector": "Local Government", "url": "https://www.bromley.gov.uk"},
    {"name": "Enfield Council", "sector": "Local Government", "url": "https://www.enfield.gov.uk"},
    {"name": "Lambeth Council", "sector": "Local Government", "url": "https://www.lambeth.gov.uk"},
    {"name": "Southwark Council", "sector": "Local Government", "url": "https://www.southwark.gov.uk"},
    {"name": "Lewisham Council", "sector": "Local Government", "url": "https://www.lewisham.gov.uk"},
    {"name": "Towerhamlets Council", "sector": "Local Government", "url": "https://www.towerhamlets.gov.uk"},
    {"name": "Hillingdon Council", "sector": "Local Government", "url": "https://www.hillingdon.gov.uk"},
    {"name": "Camden Council", "sector": "Local Government", "url": "https://www.camden.gov.uk"},
    {"name": "Redbridge Council", "sector": "Local Government", "url": "https://www.redbridge.gov.uk"},
    {"name": "Richmond Council", "sector": "Local Government", "url": "https://www.richmond.gov.uk"},
    {"name": "Haringey Council", "sector": "Local Government", "url": "https://www.haringey.gov.uk"},
    {"name": "Hackney Council", "sector": "Local Government", "url": "https://www.hackney.gov.uk"},
    {"name": "Walthamforest Council", "sector": "Local Government", "url": "https://www.walthamforest.gov.uk"},
    {"name": "Bexley Council", "sector": "Local Government", "url": "https://www.bexley.gov.uk"},
    {"name": "Hounslow Council", "sector": "Local Government", "url": "https://www.hounslow.gov.uk"},
    {"name": "Merton Council", "sector": "Local Government", "url": "https://www.merton.gov.uk"},
    {"name": "Havering Council", "sector": "Local Government", "url": "https://www.havering.gov.uk"},
    {"name": "Islington Council", "sector": "Local Government", "url": "https://www.islington.gov.uk"},
    {"name": "Greenwich Council", "sector": "Local Government", "url": "https://www.greenwich.gov.uk"},
    {"name": "Sutton Council", "sector": "Local Government", "url": "https://www.sutton.gov.uk"},
    {"name": "Harrow Council", "sector": "Local Government", "url": "https://www.harrow.gov.uk"},
    {"name": "Kensingtonandchelsea Council", "sector": "Local Government", "url": "https://www.kensingtonandchelsea.gov.uk"},
    {"name": "Westminster Council", "sector": "Local Government", "url": "https://www.westminster.gov.uk"},
    {"name": "Barking-Dagenham Council", "sector": "Local Government", "url": "https://www.barking-dagenham.gov.uk"},
    {"name": "Kingston Council", "sector": "Local Government", "url": "https://www.kingston.gov.uk"},
    {"name": "Hammersmithfulham Council", "sector": "Local Government", "url": "https://www.hammersmithfulham.gov.uk"},
    {"name": "Cornwall Council", "sector": "Local Government", "url": "https://www.cornwall.gov.uk"},
    {"name": "Durham Council", "sector": "Local Government", "url": "https://www.durham.gov.uk"},
    {"name": "Wiltshire Council", "sector": "Local Government", "url": "https://www.wiltshire.gov.uk"},
    {"name": "Northyorks Council", "sector": "Local Government", "url": "https://www.northyorks.gov.uk"},
    {"name": "Cheshireeast Council", "sector": "Local Government", "url": "https://www.cheshireeast.gov.uk"},
    {"name": "Cheshirewestandchester Council", "sector": "Local Government", "url": "https://www.cheshirewestandchester.gov.uk"},
    {"name": "Shropshire Council", "sector": "Local Government", "url": "https://www.shropshire.gov.uk"},
    {"name": "Somerset Council", "sector": "Local Government", "url": "https://www.somerset.gov.uk"},
    {"name": "Northumberland Council", "sector": "Local Government", "url": "https://www.northumberland.gov.uk"},
    {"name": "Herefordshire Council", "sector": "Local Government", "url": "https://www.herefordshire.gov.uk"},
    {"name": "Nottinghamcity Council", "sector": "Local Government", "url": "https://www.nottinghamcity.gov.uk"},
    {"name": "Newcastle Council", "sector": "Local Government", "url": "https://www.newcastle.gov.uk"},
    {"name": "Sunderland Council", "sector": "Local Government", "url": "https://www.sunderland.gov.uk"},
    {"name": "Brighton-Hove Council", "sector": "Local Government", "url": "https://www.brighton-hove.gov.uk"},
    {"name": "Hull Council", "sector": "Local Government", "url": "https://www.hull.gov.uk"},
    {"name": "Plymouth Council", "sector": "Local Government", "url": "https://www.plymouth.gov.uk"},
    {"name": "Derby Council", "sector": "Local Government", "url": "https://www.derby.gov.uk"},
    {"name": "Stoke Council", "sector": "Local Government", "url": "https://www.stoke.gov.uk"},
    {"name": "Southampton Council", "sector": "Local Government", "url": "https://www.southampton.gov.uk"},
    {"name": "Portsmouth Council", "sector": "Local Government", "url": "https://www.portsmouth.gov.uk"},
    {"name": "York Council", "sector": "Local Government", "url": "https://www.york.gov.uk"},
    {"name": "Swansea Council", "sector": "Local Government", "url": "https://www.swansea.gov.uk"},
    {"name": "Newport Council", "sector": "Local Government", "url": "https://www.newport.gov.uk"},
    {"name": "Fife Council", "sector": "Local Government", "url": "https://www.fife.gov.uk"},
    {"name": "Northlanarkshire Council", "sector": "Local Government", "url": "https://www.northlanarkshire.gov.uk"},
    {"name": "Southlanarkshire Council", "sector": "Local Government", "url": "https://www.southlanarkshire.gov.uk"},
    {"name": "Aberdeencity Council", "sector": "Local Government", "url": "https://www.aberdeencity.gov.uk"},
    {"name": "Highland Council", "sector": "Local Government", "url": "https://www.highland.gov.uk"},
    {"name": "Renfrewshire Council", "sector": "Local Government", "url": "https://www.renfrewshire.gov.uk"},
    {"name": "Falkirk Council", "sector": "Local Government", "url": "https://www.falkirk.gov.uk"},
    {"name": "Dumgal Council", "sector": "Local Government", "url": "https://www.dumgal.gov.uk"},
    {"name": "Dundeecity Council", "sector": "Local Government", "url": "https://www.dundeecity.gov.uk"},
    {"name": "Belfastcity Council", "sector": "Local Government", "url": "https://www.belfastcity.gov.uk"},
    {"name": "Derrystrabane Council", "sector": "Local Government", "url": "https://www.derrystrabane.com"},
    {"name": "Armaghbanbridgecraigavon Council", "sector": "Local Government", "url": "https://www.armaghbanbridgecraigavon.gov.uk"},
    {"name": "Midandeastantrim Council", "sector": "Local Government", "url": "https://www.midandeastantrim.gov.uk"},
    {"name": "Midulstercouncil Council", "sector": "Local Government", "url": "https://www.midulstercouncil.org"},
    {"name": "Causewaycoastandglens Council", "sector": "Local Government", "url": "https://www.causewaycoastandglens.gov.uk"},
    {"name": "Fermanaghomagh Council", "sector": "Local Government", "url": "https://www.fermanaghomagh.com"},
    {"name": "Lisburncastlereagh Council", "sector": "Local Government", "url": "https://www.lisburncastlereagh.gov.uk"},
    {"name": "Antrimandnewtownabbey Council", "sector": "Local Government", "url": "https://www.antrimandnewtownabbey.gov.uk"},
    {"name": "Ardsandnorthdown Council", "sector": "Local Government", "url": "https://www.ardsandnorthdown.gov.uk"},
    {"name": "Newrymournedown Council", "sector": "Local Government", "url": "https://www.newrymournedown.org"},
    {"name": "Hertscc Council", "sector": "Local Government", "url": "https://www.hertscc.gov.uk"},
    {"name": "Kent Council", "sector": "Local Government", "url": "https://www.kent.gov.uk"},
    {"name": "Essex Council", "sector": "Local Government", "url": "https://www.essex.gov.uk"},
    {"name": "Hants Council", "sector": "Local Government", "url": "https://www.hants.gov.uk"},
    {"name": "Lancashire Council", "sector": "Local Government", "url": "https://www.lancashire.gov.uk"},
    {"name": "Surreycc Council", "sector": "Local Government", "url": "https://www.surreycc.gov.uk"},
    {"name": "Northants Council", "sector": "Local Government", "url": "https://www.northants.gov.uk"},
    {"name": "Norfolk Council", "sector": "Local Government", "url": "https://www.norfolk.gov.uk"},
    {"name": "Westsussex Council", "sector": "Local Government", "url": "https://www.westsussex.gov.uk"},
    {"name": "Staffordshire Council", "sector": "Local Government", "url": "https://www.staffordshire.gov.uk"},
    {"name": "Derbyshire Council", "sector": "Local Government", "url": "https://www.derbyshire.gov.uk"},
    {"name": "Devon Council", "sector": "Local Government", "url": "https://www.devon.gov.uk"},
    {"name": "Oxfordshire Council", "sector": "Local Government", "url": "https://www.oxfordshire.gov.uk"},
    {"name": "Cambridgeshire Council", "sector": "Local Government", "url": "https://www.cambridgeshire.gov.uk"},
    {"name": "Gloucestershire Council", "sector": "Local Government", "url": "https://www.gloucestershire.gov.uk"},
    {"name": "Leics Council", "sector": "Local Government", "url": "https://www.leics.gov.uk"},
    {"name": "Warwickshire Council", "sector": "Local Government", "url": "https://www.warwickshire.gov.uk"},
    {"name": "Worcestershire Council", "sector": "Local Government", "url": "https://www.worcestershire.gov.uk"},
    {"name": "Eastsussex Council", "sector": "Local Government", "url": "https://www.eastsussex.gov.uk"},
    {"name": "Cumbria Council", "sector": "Local Government", "url": "https://www.cumbria.gov.uk"},
    {"name": "Suffolk Council", "sector": "Local Government", "url": "https://www.suffolk.gov.uk"},
    {"name": "Buckinghamshire Council", "sector": "Local Government", "url": "https://www.buckinghamshire.gov.uk"},
    {"name": "Dorsetcouncil Council", "sector": "Local Government", "url": "https://www.dorsetcouncil.gov.uk"},
    {"name": "Coventry Council", "sector": "Local Government", "url": "https://www.coventry.gov.uk"},
    {"name": "Wolverhampton Council", "sector": "Local Government", "url": "https://www.wolverhampton.gov.uk"},
    {"name": "Dudley Council", "sector": "Local Government", "url": "https://www.dudley.gov.uk"},
    {"name": "Sandwell Council", "sector": "Local Government", "url": "https://www.sandwell.gov.uk"},
    {"name": "Walsall Council", "sector": "Local Government", "url": "https://www.walsall.gov.uk"},
    {"name": "Solihull Council", "sector": "Local Government", "url": "https://www.solihull.gov.uk"},

    # --- 120 MAJOR NHS TRUSTS & HEALTH BOARDS ---
    {"name": "Bartshealth NHS Trust", "sector": "NHS", "url": "https://www.bartshealth.nhs.uk"},
    {"name": "Guysandstthomas NHS Trust", "sector": "NHS", "url": "https://www.guysandstthomas.nhs.uk"},
    {"name": "Uclh NHS Trust", "sector": "NHS", "url": "https://www.uclh.nhs.uk"},
    {"name": "Imperial NHS Trust", "sector": "NHS", "url": "https://www.imperial.nhs.uk"},
    {"name": "Kingscollegehospital NHS Trust", "sector": "NHS", "url": "https://www.kingscollegehospital.nhs.uk"},
    {"name": "Nuh NHS Trust", "sector": "NHS", "url": "https://www.nuh.nhs.uk"},
    {"name": "Uhb NHS Trust", "sector": "NHS", "url": "https://www.uhb.nhs.uk"},
    {"name": "Mft NHS Trust", "sector": "NHS", "url": "https://www.mft.nhs.uk"},
    {"name": "Leedsth NHS Trust", "sector": "NHS", "url": "https://www.leedsth.nhs.uk"},
    {"name": "Uhs NHS Trust", "sector": "NHS", "url": "https://www.uhs.nhs.uk"},
    {"name": "Uhcw NHS Trust", "sector": "NHS", "url": "https://www.uhcw.nhs.uk"},
    {"name": "Cuh NHS Trust", "sector": "NHS", "url": "https://www.cuh.nhs.uk"},
    {"name": "Ouh NHS Trust", "sector": "NHS", "url": "https://www.ouh.nhs.uk"},
    {"name": "Nuth NHS Trust", "sector": "NHS", "url": "https://www.nuth.nhs.uk"},
    {"name": "Stgeorges NHS Trust", "sector": "NHS", "url": "https://www.stgeorges.nhs.uk"},
    {"name": "Royalfree NHS Trust", "sector": "NHS", "url": "https://www.royalfree.nhs.uk"},
    {"name": "Chelwest NHS Trust", "sector": "NHS", "url": "https://www.chelwest.nhs.uk"},
    {"name": "Lnwh NHS Trust", "sector": "NHS", "url": "https://www.lnwh.nhs.uk"},
    {"name": "Bhrhospitals NHS Trust", "sector": "NHS", "url": "https://www.bhrhospitals.nhs.uk"},
    {"name": "Epsom-Sthelier NHS Trust", "sector": "NHS", "url": "https://www.epsom-sthelier.nhs.uk"},
    {"name": "Croydonhealthservices NHS Trust", "sector": "NHS", "url": "https://www.croydonhealthservices.nhs.uk"},
    {"name": "Homerton NHS Trust", "sector": "NHS", "url": "https://www.homerton.nhs.uk"},
    {"name": "Whittington NHS Trust", "sector": "NHS", "url": "https://www.whittington.nhs.uk"},
    {"name": "Hillingdon NHS Trust", "sector": "NHS", "url": "https://www.hillingdon.nhs.uk"},
    {"name": "Lewishamandgreenwich NHS Trust", "sector": "NHS", "url": "https://www.lewishamandgreenwich.nhs.uk"},
    {"name": " Kingstonhospital NHS Trust", "sector": "NHS", "url": "https://www. Kingstonhospital.nhs.uk"},
    {"name": "Ruh NHS Trust", "sector": "NHS", "url": "https://www.ruh.nhs.uk"},
    {"name": "Nbt NHS Trust", "sector": "NHS", "url": "https://www.nbt.nhs.uk"},
    {"name": "Gosh NHS Trust", "sector": "NHS", "url": "https://www.gosh.nhs.uk"},
    {"name": "Rmh NHS Trust", "sector": "NHS", "url": "https://www.rmh.nhs.uk"},
    {"name": "Moorfields NHS Trust", "sector": "NHS", "url": "https://www.moorfields.nhs.uk"},
    {"name": "Rnoh NHS Trust", "sector": "NHS", "url": "https://www.rnoh.nhs.uk"},
    {"name": "Tavistockandportman NHS Trust", "sector": "NHS", "url": "https://www.tavistockandportman.nhs.uk"},
    {"name": "Broadmoor NHS Trust", "sector": "NHS", "url": "https://www.broadmoor.nhs.uk"},
    {"name": "Rampton NHS Trust", "sector": "NHS", "url": "https://www.rampton.nhs.uk"},
    {"name": "Ashworth NHS Trust", "sector": "NHS", "url": "https://www.ashworth.nhs.uk"},
    {"name": "Derbyhospitals NHS Trust", "sector": "NHS", "url": "https://www.derbyhospitals.nhs.uk"},
    {"name": "Chesterfieldroyal NHS Trust", "sector": "NHS", "url": "https://www.chesterfieldroyal.nhs.uk"},
    {"name": "Sfh-Tr NHS Trust", "sector": "NHS", "url": "https://www.sfh-tr.nhs.uk"},
    {"name": "Ulh NHS Trust", "sector": "NHS", "url": "https://www.ulh.nhs.uk"},
    {"name": "Uhl-Tr NHS Trust", "sector": "NHS", "url": "https://www.uhl-tr.nhs.uk"},
    {"name": "Kgh NHS Trust", "sector": "NHS", "url": "https://www.kgh.nhs.uk"},
    {"name": "Ngh NHS Trust", "sector": "NHS", "url": "https://www.ngh.nhs.uk"},
    {"name": "Nnuh NHS Trust", "sector": "NHS", "url": "https://www.nnuh.nhs.uk"},
    {"name": "Jpaget NHS Trust", "sector": "NHS", "url": "https://www.jpaget.nhs.uk"},
    {"name": "Qehkl NHS Trust", "sector": "NHS", "url": "https://www.qehkl.nhs.uk"},
    {"name": "Wsh NHS Trust", "sector": "NHS", "url": "https://www.wsh.nhs.uk"},
    {"name": "Ipswichhospital NHS Trust", "sector": "NHS", "url": "https://www.ipswichhospital.nhs.uk"},
    {"name": "Colchesterhospital NHS Trust", "sector": "NHS", "url": "https://www.colchesterhospital.nhs.uk"},
    {"name": "Meht NHS Trust", "sector": "NHS", "url": "https://www.meht.nhs.uk"},
    {"name": "Southend NHS Trust", "sector": "NHS", "url": "https://www.southend.nhs.uk"},
    {"name": "Btuh NHS Trust", "sector": "NHS", "url": "https://www.btuh.nhs.uk"},
    {"name": "Pah NHS Trust", "sector": "NHS", "url": "https://www.pah.nhs.uk"},
    {"name": "Enherts-Tr NHS Trust", "sector": "NHS", "url": "https://www.enherts-tr.nhs.uk"},
    {"name": "Whht NHS Trust", "sector": "NHS", "url": "https://www.whht.nhs.uk"},
    {"name": "Ldh NHS Trust", "sector": "NHS", "url": "https://www.ldh.nhs.uk"},
    {"name": "Bedfordhospital NHS Trust", "sector": "NHS", "url": "https://www.bedfordhospital.nhs.uk"},
    {"name": "Mkuh NHS Trust", "sector": "NHS", "url": "https://www.mkuh.nhs.uk"},
    {"name": "Buckshealthcare NHS Trust", "sector": "NHS", "url": "https://www.buckshealthcare.nhs.uk"},
    {"name": "Royalberkshire NHS Trust", "sector": "NHS", "url": "https://www.royalberkshire.nhs.uk"},
    {"name": "Frimleyhealth NHS Trust", "sector": "NHS", "url": "https://www.frimleyhealth.nhs.uk"},
    {"name": "Asph NHS Trust", "sector": "NHS", "url": "https://www.asph.nhs.uk"},
    {"name": "Rsch NHS Trust", "sector": "NHS", "url": "https://www.rsch.nhs.uk"},
    {"name": "Sash NHS Trust", "sector": "NHS", "url": "https://www.sash.nhs.uk"},
    {"name": "Ekhuft NHS Trust", "sector": "NHS", "url": "https://www.ekhuft.nhs.uk"},
    {"name": "Mtw NHS Trust", "sector": "NHS", "url": "https://www.mtw.nhs.uk"},
    {"name": "Medway NHS Trust", "sector": "NHS", "url": "https://www.medway.nhs.uk"},
    {"name": "Dvh NHS Trust", "sector": "NHS", "url": "https://www.dvh.nhs.uk"},
    {"name": "Esht NHS Trust", "sector": "NHS", "url": "https://www.esht.nhs.uk"},
    {"name": "Bsuh NHS Trust", "sector": "NHS", "url": "https://www.bsuh.nhs.uk"},
    {"name": "Wsht NHS Trust", "sector": "NHS", "url": "https://www.wsht.nhs.uk"},
    {"name": "Porthosp NHS Trust", "sector": "NHS", "url": "https://www.porthosp.nhs.uk"},
    {"name": "Iow NHS Trust", "sector": "NHS", "url": "https://www.iow.nhs.uk"},
    {"name": "Salisbury NHS Trust", "sector": "NHS", "url": "https://www.salisbury.nhs.uk"},
    {"name": "Dchft NHS Trust", "sector": "NHS", "url": "https://www.dchft.nhs.uk"},
    {"name": "Poole NHS Trust", "sector": "NHS", "url": "https://www.poole.nhs.uk"},
    {"name": "Rbch NHS Trust", "sector": "NHS", "url": "https://www.rbch.nhs.uk"},
    {"name": "Tst NHS Trust", "sector": "NHS", "url": "https://www.tst.nhs.uk"},
    {"name": "Ydh NHS Trust", "sector": "NHS", "url": "https://www.ydh.nhs.uk"},
    {"name": "Rdehospital NHS Trust", "sector": "NHS", "url": "https://www.rdehospital.nhs.uk"},
    {"name": "Ndht NHS Trust", "sector": "NHS", "url": "https://www.ndht.nhs.uk"},
    {"name": "Torbayandsouthdevon NHS Trust", "sector": "NHS", "url": "https://www.torbayandsouthdevon.nhs.uk"},
    {"name": "Plymouthhospitals NHS Trust", "sector": "NHS", "url": "https://www.plymouthhospitals.nhs.uk"},
    {"name": "Rcht NHS Trust", "sector": "NHS", "url": "https://www.rcht.nhs.uk"},
    {"name": "Gloshospitals NHS Trust", "sector": "NHS", "url": "https://www.gloshospitals.nhs.uk"},
    {"name": "Wvt NHS Trust", "sector": "NHS", "url": "https://www.wvt.nhs.uk"},
    {"name": "Wyevalley NHS Trust", "sector": "NHS", "url": "https://www.wyevalley.nhs.uk"},
    {"name": "Sath NHS Trust", "sector": "NHS", "url": "https://www.sath.nhs.uk"},
    {"name": "Uhnm NHS Trust", "sector": "NHS", "url": "https://www.uhnm.nhs.uk"},
    {"name": "Dgft NHS Trust", "sector": "NHS", "url": "https://www.dgft.nhs.uk"},
    {"name": "Walsallhealthcare NHS Trust", "sector": "NHS", "url": "https://www.walsallhealthcare.nhs.uk"},
    {"name": "Swbh NHS Trust", "sector": "NHS", "url": "https://www.swbh.nhs.uk"},
    {"name": "Geh NHS Trust", "sector": "NHS", "url": "https://www.geh.nhs.uk"},
    {"name": "Swft NHS Trust", "sector": "NHS", "url": "https://www.swft.nhs.uk"},
    {"name": "Worcsacute NHS Trust", "sector": "NHS", "url": "https://www.worcsacute.nhs.uk"},
    {"name": "Nhsggc NHS Trust", "sector": "NHS", "url": "https://www.nhsggc.org.uk"},
    {"name": "Nhslothian NHS Trust", "sector": "NHS", "url": "https://www.nhslothian.scot"},
    {"name": "Nhsgrampian NHS Trust", "sector": "NHS", "url": "https://www.nhsgrampian.org"},
    {"name": "Nhstayside NHS Trust", "sector": "NHS", "url": "https://www.nhstayside.scot.nhs.uk"},
    {"name": "Nhslanarkshire NHS Trust", "sector": "NHS", "url": "https://www.nhslanarkshire.scot.nhs.uk"},
    {"name": "Nhsfife NHS Trust", "sector": "NHS", "url": "https://www.nhsfife.org"},
    {"name": "Nhsforthvalley NHS Trust", "sector": "NHS", "url": "https://www.nhsforthvalley.com"},
    {"name": "Nhsayrshireandarran NHS Trust", "sector": "NHS", "url": "https://www.nhsayrshireandarran.com"},
    {"name": "Nhshighland NHS Trust", "sector": "NHS", "url": "https://www.nhshighland.scot.nhs.uk"},
    {"name": "Nhsdg NHS Trust", "sector": "NHS", "url": "https://www.nhsdg.co.uk"},
    {"name": "Nhsborders NHS Trust", "sector": "NHS", "url": "https://www.nhsborders.scot.nhs.uk"},
    {"name": "Wales NHS Trust", "sector": "NHS", "url": "https://www.wales.nhs.uk"},
    {"name": "Cardiffandvaleuhb NHS Trust", "sector": "NHS", "url": "https://www.cardiffandvaleuhb.wales.nhs.uk"},
    {"name": "Abmu NHS Trust", "sector": "NHS", "url": "https://www.abmu.wales.nhs.uk"},
    {"name": "Aneurinbevanhb NHS Trust", "sector": "NHS", "url": "https://www.aneurinbevanhb.wales.nhs.uk"},
    {"name": "Hywelddahb NHS Trust", "sector": "NHS", "url": "https://www.hywelddahb.wales.nhs.uk"},
    {"name": "Cwmtaf NHS Trust", "sector": "NHS", "url": "https://www.cwmtaf.wales.nhs.uk"},
    {"name": "Belfasttrust NHS Trust", "sector": "NHS", "url": "https://www.belfasttrust.hscni.net"},
    {"name": "Setrust NHS Trust", "sector": "NHS", "url": "https://www.setrust.hscni.net"},
    {"name": "Southerntrust NHS Trust", "sector": "NHS", "url": "https://www.southerntrust.hscni.net"},
    {"name": "Northerntrust NHS Trust", "sector": "NHS", "url": "https://www.northerntrust.hscni.net"},
    {"name": "Westerntrust NHS Trust", "sector": "NHS", "url": "https://www.westerntrust.hscni.net"}
] # # #

class SourceDispatchAgent(BaseAgent):
    def __init__(self, broker=None):
        super().__init__("source_dispatch_agent", "company_list_queue")

    def _resolve_portals(self, universe_str: str) -> list[dict]:
        if not universe_str or universe_str.lower() in ("all", "public sector"):
            return PUBLIC_SECTOR_PORTALS
        
        target_names = [p.strip().lower() for p in universe_str.split(",")]
        resolved = []
        for portal in PUBLIC_SECTOR_PORTALS:
            name = portal["name"].lower()
            sector = portal["sector"].lower()
            if any(t in name or t in sector for t in target_names):
                resolved.append(portal)
        return resolved

    def process_message(self, message: dict):
        logger.info(f"[{self.name}] Received dispatch request: {message}")
        payload = message.get("payload", {})
        workflow_id = message.get("correlation_id") or payload.get("workflow_id")
        params = payload.get("params", {})
        universe = params.get("universe", "All")
        
        portals_to_search = self._resolve_portals(universe)
        
        limit = payload.get("limit")
        if limit and limit > 0:
            portals_to_search = portals_to_search[:limit]
            
        logger.info(f"[{self.name}] Discovered {len(portals_to_search)} portals to search.")
        
        if not portals_to_search:
            self.broker.publish(queue_name="master_queue", source=self.name, target="master", msg_type="task_response", correlation_id=workflow_id, payload={
                "type": "stage_1_complete",
                "workflow_id": workflow_id,
                "companies": [],
                "portals": [],
                "searches_dispatched": 0
            })
            return

        for portal in portals_to_search:
            search_msg = {
                "workflow_id": workflow_id,
                "portal": portal,
                "params": params,
                "include_entry_level": payload.get("include_entry_level", True)
            }
            self.broker.publish(queue_name="job_search_queue", source=self.name, target="job_search_agent", msg_type="task_request", correlation_id=workflow_id, payload=search_msg)
            
        self.broker.publish(queue_name="master_queue", source=self.name, target="master", msg_type="task_response", correlation_id=workflow_id, payload={
            "type": "stage_1_complete",
            "workflow_id": workflow_id,
            "portals": portals_to_search,
            "companies": portals_to_search,
            "searches_dispatched": len(portals_to_search)
        })
